### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by DoYouBelieveInTheUsers** [DoYouBelieveInTheUsers/atom-maya-quick-help#1]
[Enter steps to reproduce:]

1. Install package from Atom Install Pacakage page
2. ...

**Atom**: 1.23.2 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-maya-quick-help](https://github.com/DoYouBelieveInTheUsers/atom-maya-quick-help) package 0.1.0

### Stack Trace

Uncaught Error: Cannot find module 'jquery'

```
At C:\Users\ukgking\AppData\Local\atom\app-1.23.2\resources\app\static\<embedded>:1

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-maya-quick-help/lib/atom-maya-quick-help.coffee:2:5)
    at /packages/atom-maya-quick-help/lib/atom-maya-quick-help.coffee:2:1)
    at /packages/atom-maya-quick-help/lib/atom-maya-quick-help.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.23.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.23.2/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:937:35)
    at Package.module.exports.Package.activateConfig (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:303:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at ~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-manager.js:703:33)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-manager.js:542:32
    at exit (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.23.2/resources/app/src/buffered-process.js:338:17)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.23.2/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  6x -0:38.4.0 core:backspace (input.hidden-input)
     -0:32.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-maya-quick-help 0.1.0 
atom-python-run 0.9.1 
autocomplete-python 1.10.2 
busy-signal 1.4.3 
highlight-selected 0.12.0 
intentions 1.1.2 
language-autohotkey2 1.0.1 
language-mel 0.1.2 
linter 2.2.0 
linter-javac 1.9.4 
linter-pylint 2.1.0 
linter-ui-default 1.6.2 
Maya 0.18.0 
nav-panel 0.0.11 
python-tools 0.6.9 
symbols-tree-view 0.14.0 
tabs-to-spaces 1.0.3 
tortoise-svn 0.5.0 
```

**Comment by DoYouBelieveInTheUsers** [comment]
Looks like node_modules wasn't committed. No idea how I've managed that.

**Comment by DoYouBelieveInTheUsers** [comment]
Noob error it seems. I didn't know node_modules wasn't supposed to be committed with the rest of the project files.

Updated project dependencies, done a bit of file shuffling and all seems to be working now

Closing
